package jappan.model;
// Generated Jul 15, 2021, 10:46:24 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chapter generated by hbm2java
 */
public class Chapter implements java.io.Serializable {

	private Integer id;
	private Course course;
	private String chapterName;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;
	private Set lessions = new HashSet(0);
	private Integer courseId;

	public Chapter() {
	}

	public Chapter(Course course, String chapterName, int activeFlag, Date createDate, Date updateDate) {
		this.course = course;
		this.chapterName = chapterName;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Chapter(Course course, String chapterName, int activeFlag, Date createDate, Date updateDate, Set lessions) {
		this.course = course;
		this.chapterName = chapterName;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.lessions = lessions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getChapterName() {
		return this.chapterName;
	}

	public void setChapterName(String chapterName) {
		this.chapterName = chapterName;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getLessions() {
		return this.lessions;
	}

	public void setLessions(Set lessions) {
		this.lessions = lessions;
	}

	public Integer getCourseId() {
		return courseId;
	}

	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}
	
	
}
