package jappan.model;
// Generated Jul 15, 2021, 10:46:24 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private Integer id;
	private String courseName;
	private String description;
	private String time;
	private String linkVideo;
	private String urlWeb;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;
	private Set chapters = new HashSet(0);

	public Course() {
	}

	public Course(String courseName, String description, String time, String linkVideo, String urlWeb, int activeFlag,
			Date createDate, Date updateDate) {
		this.courseName = courseName;
		this.description = description;
		this.time = time;
		this.linkVideo = linkVideo;
		this.urlWeb = urlWeb;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Course(String courseName, String description, String time, String linkVideo, String urlWeb, int activeFlag,
			Date createDate, Date updateDate, Set chapters) {
		this.courseName = courseName;
		this.description = description;
		this.time = time;
		this.linkVideo = linkVideo;
		this.urlWeb = urlWeb;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.chapters = chapters;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getLinkVideo() {
		return this.linkVideo;
	}

	public void setLinkVideo(String linkVideo) {
		this.linkVideo = linkVideo;
	}

	public String getUrlWeb() {
		return this.urlWeb;
	}

	public void setUrlWeb(String urlWeb) {
		this.urlWeb = urlWeb;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public Set getChapters() {
		return this.chapters;
	}

	public void setChapters(Set chapters) {
		this.chapters = chapters;
	}

}
