package jappan.model;
// Generated Jul 15, 2021, 10:46:24 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Exam generated by hbm2java
 */
public class Exam implements java.io.Serializable {

	private Integer id;
	private ExamPart examPart;
	private Level level;
	private String name;
	private String description;
	private String duration;
	private String linkAudio;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;
	private Set questions = new HashSet(0);
	private Set histories = new HashSet(0);

	public Exam() {
	}

	public Exam(ExamPart examPart, Level level, String name, String description, int activeFlag, Date createDate,
			Date updateDate) {
		this.examPart = examPart;
		this.level = level;
		this.name = name;
		this.description = description;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Exam(ExamPart examPart, Level level, String name, String description, String duration, String linkAudio,
			int activeFlag, Date createDate, Date updateDate, Set questions, Set histories) {
		this.examPart = examPart;
		this.level = level;
		this.name = name;
		this.description = description;
		this.duration = duration;
		this.linkAudio = linkAudio;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.questions = questions;
		this.histories = histories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public ExamPart getExamPart() {
		return this.examPart;
	}

	public void setExamPart(ExamPart examPart) {
		this.examPart = examPart;
	}

	public Level getLevel() {
		return this.level;
	}

	public void setLevel(Level level) {
		this.level = level;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public String getLinkAudio() {
		return this.linkAudio;
	}

	public void setLinkAudio(String linkAudio) {
		this.linkAudio = linkAudio;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}
	
	public Set getQuestions() {
		return this.questions;
	}

	public void setQuestions(Set questions) {
		this.questions = questions;
	}

	public Set getHistories() {
		return this.histories;
	}

	public void setHistories(Set histories) {
		this.histories = histories;
	}

}
