package jappan.model;
// Generated Jul 15, 2021, 10:46:24 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * History generated by hbm2java
 */
public class History implements java.io.Serializable {

	private Integer id;
	private Exam exam;
	private Users users;
	private int goibunpou;
	private int dokkai;
	private int choukai;
	private int activeFlag;
	private Date createDate;
	private Date updateDate;

	public History() {
	}

	public History(Exam exam, Users users, int goibunpou, int dokkai, int choukai, int activeFlag, Date createDate,
			Date updateDate) {
		this.exam = exam;
		this.users = users;
		this.goibunpou = goibunpou;
		this.dokkai = dokkai;
		this.choukai = choukai;
		this.activeFlag = activeFlag;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Exam getExam() {
		return this.exam;
	}

	public void setExam(Exam exam) {
		this.exam = exam;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getGoibunpou() {
		return this.goibunpou;
	}

	public void setGoibunpou(int goibunpou) {
		this.goibunpou = goibunpou;
	}

	public int getDokkai() {
		return this.dokkai;
	}

	public void setDokkai(int dokkai) {
		this.dokkai = dokkai;
	}

	public int getChoukai() {
		return this.choukai;
	}

	public void setChoukai(int choukai) {
		this.choukai = choukai;
	}

	public int getActiveFlag() {
		return this.activeFlag;
	}

	public void setActiveFlag(int activeFlag) {
		this.activeFlag = activeFlag;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
